"""Pydantic v2 models for runtime validation and serialization.

Separate from types.py (TypedDict) — these provide actual runtime
validation when used at node boundaries or for JSON serialization.
"""

from __future__ import annotations

import yaml
import re
from typing import Optional, Any

from pydantic import BaseModel, Field, field_validator, ValidationError


# ── Individual schemas ──────────────────────────────────────────


class Persona(BaseModel):
    """A debate participant persona generated by InitNode."""
    model_config = {"extra": "forbid"}

    name: str = Field(..., min_length=1, description="Full realistic name")
    role: str = Field(..., min_length=2, max_length=60, description="2-5 word job title")
    perspective: str = Field(..., min_length=15, description="Core belief with fear/hope")
    reasoning_approach: str = Field(
        default="Evidence-first",
        description="One of: Evidence-first, Principle-first, Counterfactual, Systems-thinking",
    )
    belief_intensity: int = Field(default=5, ge=1, le=10)
    communication_style: str = Field(default="", description="How they argue")
    argument_tendency: str = Field(default="", description="Their signature move")

    @field_validator("belief_intensity", mode="before")
    @classmethod
    def coerce_intensity(cls, v: object) -> int:
        """LLMs sometimes return strings — coerce to int."""
        try:
            return int(v)  # pyright: ignore[reportArgumentType]
        except (TypeError, ValueError):
            return 5  # sensible default on unparseable intensity


class Message(BaseModel):
    """A single turn in the conversation."""
    agent: str
    message: str


class ModeratorIntervention(BaseModel):
    """A moderator intervention log entry."""
    turn: int
    loop_detected: bool = False
    drift_detected: bool = False
    note: str
    stall_count: int = 0


class ResearchFindings(BaseModel):
    """Fact-check findings from ResearchNode."""
    turn: int
    findings: dict[str, Any] = Field(default_factory=dict)


# ── Shared store model —─────────────────────────────────────────


class SharedStore(BaseModel):
    """Validated shared store passed between PocketFlow nodes.

    All fields with defaults reflect the initial state. Fields
    without defaults are populated during flow execution.
    """
    model_config = {"extra": "forbid"}

    topic: str
    personas: list[Persona] = Field(default_factory=list)
    conversation: list[Message] = Field(default_factory=list)
    turn: int = 0
    max_turns: int = Field(default=50, ge=1)
    last_speaker: Optional[str] = None
    moderator_notes: Optional[str] = None
    moderator_interventions: list[ModeratorIntervention] = Field(default_factory=list)
    next_speaker: Optional[str] = None
    speaker_turns: dict[str, int] = Field(default_factory=dict)
    stall_count: int = 0
    research_count: int = 0
    research_notes: list[ResearchFindings] = Field(default_factory=list)
    summary: str = ""

    @field_validator("max_turns")
    @classmethod
    def max_turns_range(cls, v: int) -> int:
        if not 1 <= v <= 500:
            raise ValueError("max_turns must be between 1 and 500")
        return v


# ── Validation utilities ────────────────────────────────────────


def parse_llm_yaml(llm_response: str) -> dict[str, Any]:
    """Extract and parse a ```yaml code block from an LLM response.

    Args:
        llm_response: Raw LLM response string.

    Returns:
        Parsed YAML dictionary.

    Raises:
        ValueError: If no YAML block found or parsing fails.
    """
    match = re.search(r"```yaml\s*\n?(.*?)```", llm_response, re.DOTALL)
    if match:
        return yaml.safe_load(match.group(1))
    # Fallback: try parsing the whole response as YAML
    return yaml.safe_load(llm_response)


def validate_personas(llm_response: str) -> list[Persona]:
    """Parse LLM response and validate personas list.

    Used by InitNode.exec() to ensure generated personas are valid.

    Args:
        llm_response: Raw LLM response containing YAML with "personas" key.

    Returns:
        List of validated Persona models.

    Raises:
        ValueError: If parsing fails or validation fails.
    """
    data = parse_llm_yaml(llm_response)
    if "personas" not in data:
        raise ValueError(f"LLM response missing 'personas' key: {llm_response[:200]}")
    if "opening_question" not in data:
        raise ValueError(f"LLM response missing 'opening_question' key: {llm_response[:200]}")

    return [Persona.model_validate(p) for p in data["personas"]]


def format_validation_error(exc: ValidationError) -> str:
    """Convert Pydantic ValidationError to a human-readable string.

    Args:
        exc: The ValidationError to format.

    Returns:
        Formatted error message with field paths and messages.
    """
    lines = []
    for error in exc.errors():
        field_path = " → ".join(str(loc) for loc in error["loc"])
        lines.append(f"  • {field_path}: {error['msg']} (input={error['input']!r})")
    return "\n".join(lines)
