# LLM defaults
DEFAULT_MAX_TOKENS = 2048
DEFAULT_TEMPERATURE = 0.7
MODERATOR_MAX_TOKENS = 1024
MODERATOR_TEMPERATURE = 0.3
INIT_TEMPERATURE = 0.9
RESEARCH_TEMPERATURE = 0.2
RESEARCH_MAX_TOKENS = 1536
SUMMARIZER_TEMPERATURE = 0.5
SUMMARIZER_MAX_TOKENS = 4096
AGENT_SPEAK_TEMPERATURE = 0.85

# Conversation limits
CONVERSATION_TRUNCATION_THRESHOLD = 30
CONVERSATION_TRUNCATION_HEAD = 10
CONVERSATION_TRUNCATION_TAIL = 15
SUMMARY_MAX_CHARS = 8000

# Moderator
STALL_HYSTERESIS_THRESHOLD = 3
RESEARCH_MAX_COUNT = 2

# Search
WEB_SEARCH_MAX_RESULTS = 3
SEARCH_RATE_LIMIT_INTERVAL = 1.2

# Personas
DEFAULT_PERSONA_COUNT = 4

# Shared store keys
TOPIC = "topic"
PERSONAS = "personas"
CONVERSATION = "conversation"
TURN = "turn"
MAX_TURNS = "max_turns"
LAST_SPEAKER = "last_speaker"
MODERATOR_NOTES = "moderator_notes"
MODERATOR_INTERVENTIONS = "moderator_interventions"
NEXT_SPEAKER = "next_speaker"
SPEAKER_TURNS = "speaker_turns"
STALL_COUNT = "stall_count"
RESEARCH_COUNT = "research_count"
RESEARCH_NOTES = "research_notes"
SUMMARY = "summary"

# API
OPENROUTER_API_URL = "https://openrouter.ai/api/v1/chat/completions"
DEFAULT_MODEL = "google/gemini-2.5-flash"
DEFAULT_HTTP_TIMEOUT = 30.0

# Error classification
RETRYABLE_HTTP_STATUSES = {429, 500, 502, 503, 504}
PERMANENT_HTTP_STATUSES = {400, 401, 402, 403, 404, 405}
